name: picture_button
description: "Flutter PictureButton Widget, If you just put the image inside PictureButton, you can use it like a other button"
version: 0.1.1
repository: https://github.com/b3lon9/picture_button

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter