name: picture_button
description: "Flutter PictureButton Widget, If you just put the image inside PictureButton, you can use it like a other button"
version: 0.0.2
repository: https://github.com/b3lon9/picture_button

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
